<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>CustomFileDownloader.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Downloader.Core\Downloader.Core.csproj" />
    <Compile Include="..\..\src\Downloader.Host\Messages.cs" Link="Host\Messages.cs" />
  </ItemGroup>

</Project>